

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**

        - id: TOLL-SERVICE
          uri: lb://TOLL-SERVICE
          predicates:
            - Path=/tolls/**

        - id: CHALLAN-SERVICE
          uri: lb://CHALLAN-SERVICE
          predicates:
            - Path=/challans/**





    eureka:
      instance:
        prefer-ip-address: true
      client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
          defaultZone: http://localhost:8761/eureka

